# Use an official Python runtime based on Debian 10 "buster" as a parent image.
FROM python:3.10.5-slim-buster

# Install OpenSSH and set the password for root to "Docker!". In this example, "apk add" is the install instruction for an Alpine Linux-based image.
RUN apt-get update --yes --quiet
RUN apt-get install --yes openssh-server
# setup SSH
RUN mkdir -p /home/LogFiles \
     && echo "root:Docker!" | chpasswd \
     && echo "cd /app" >> /etc/bash.bashrc 

# Copy the sshd_config file to the /etc/ssh/ directory
COPY sshd_config /etc/ssh/


# Open port 2222 for SSH access
ENV SSH_PORT 2222
RUN sed -i "s/SSH_PORT/$SSH_PORT/g" /etc/ssh/sshd_config

# Add user that will be used in the container.
# RUN useradd wagtail

# Port used by this container to serve HTTP.
EXPOSE 8000 2222

# Set environment variables.
# 1. Force Python stdout and stderr streams to be unbuffered.
# 2. Set PORT variable that is used by Gunicorn. This should match "EXPOSE"
#    command.
ENV PYTHONUNBUFFERED=1 \
    PORT=8000

# Install system packages required by Wagtail and Django.
RUN apt-get install --yes --quiet --no-install-recommends \
    build-essential \
    libpq-dev \
    libmariadbclient-dev \
    libjpeg62-turbo-dev \
    zlib1g-dev \
    libwebp-dev \
 && rm -rf /var/lib/apt/lists/*

# Install the application server.
RUN pip install "gunicorn==20.0.4"

# Install the project requirements.
COPY requirements.txt /
RUN pip install -r /requirements.txt

# Use /app folder as a directory where the source code is stored.
WORKDIR /app

# Set this directory to be owned by the "wagtail" user. This Wagtail project
# uses SQLite, the folder needs to be owned by the user that
# will be writing to the database file.
# RUN chown wagtail:wagtail /app

# Copy the source code of the project into the container.
# COPY --chown=wagtail:wagtail . .
COPY . .

# Use user "wagtail" to run the build commands below and the server itself.
# USER wagtail

# Collect static files.
RUN python manage.py collectstatic --noinput --clear

# Runtime command that executes when "docker run" is called, it does the
# following:
#   1. Migrate the database.
#   2. Start the application server.
# WARNING:
#   Migrating database at the same time as starting the server IS NOT THE BEST
#   PRACTICE. The database should be migrated manually or using the release
#   phase facilities of your hosting platform. This is used only so the
#   Wagtail instance can be started with a simple "docker run" command.
CMD service ssh start; set -xe; python manage.py migrate --noinput; gunicorn jvcms.wsgi:application




### !!!!!!!!!!!! ADDDFILE
# This is ssh server systemwide configuration file.
#
# /etc/sshd_config
# Port 			SSH_PORT
# ListenAddress 		0.0.0.0
# LoginGraceTime 		180
# X11Forwarding 		yes
# Ciphers aes128-cbc,3des-cbc,aes256-cbc,aes128-ctr,aes192-ctr,aes256-ctr
# MACs hmac-sha1,hmac-sha1-96
# StrictModes 		yes
# SyslogFacility 		DAEMON
# PasswordAuthentication 	yes
# PermitEmptyPasswords 	no
# PermitRootLogin 	yes
# Subsystem sftp internal-sftp