version: '3.9' 
services:
  app:
    image: jevillanueva/jvcms:latest
    ports:
      - "80:8000"
    volumes:
      - type: volume
        source: mymedia
        target: /app/mymedia
      - type: volume
        source: mydb
        target: /app/db
volumes:
  mymedia:
  mydb: