version: '3.9' 
services:
  app:
    image: jevillanueva/jvcms:latest
    ports:
      - "80:8000"
      - "443:8000"
      - "2222:2222" #For SSH access
    volumes:
      - type: volume
        source: mymedia
        target: /app/media
      - type: volume
        source: mydb
        target: /app/db
volumes:
  mymedia:
  mydb: