version: '3.9' 
volumes:
  app_media: {}
  db_data: {}
services:
  web:
    image: nginx:alpine 
    volumes:
      - ./nginx/production/backend.conf:/etc/nginx/conf.d/default.conf
      - app_media:/app/media
    labels:
      - traefik.http.routers.blog.rule=Host(`${TRAEFIK_APP_DOMAIN}`)
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=lets-encrypt
      - traefik.port=${TRAEFIK_APP_PORT}
    networks:
      - web
      - internal
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - traefik.enable=false
    expose:
      - "8000"
    volumes:
      - app_media:/app/media
    env_file:
      - backend.env
    networks:
      - internal
    depends_on:
      - database
  database:
    image: mysql:5.7
    labels:
      - traefik.enable=false
    env_file:
      - database.env
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
networks:
  web:
    external: true
  internal:
    external: false