# Generated by Django 3.2.12 on 2022-02-11 03:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortafolioIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('name', wagtail.core.fields.RichTextField(blank=True)),
                ('jobTitle', wagtail.core.fields.RichTextField(blank=True)),
                ('email', wagtail.core.fields.RichTextField()),
                ('phone', wagtail.core.fields.RichTextField(blank=True)),
                ('summary', wagtail.core.fields.RichTextField(blank=True)),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
