# Generated by Django 3.2.12 on 2022-02-11 17:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_portafolioindex_employmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolioindex',
            name='employmentHistory',
            field=wagtail.core.fields.StreamField([('employ', wagtail.core.blocks.StructBlock([('jobTitle', wagtail.core.blocks.CharBlock(blank=True)), ('employer', wagtail.core.blocks.CharBlock(blank=True)), ('city', wagtail.core.blocks.CharBlock(blank=True)), ('description', wagtail.core.blocks.CharBlock(blank=True)), ('initDate', wagtail.core.blocks.DateBlock(blank=True)), ('endDate', wagtail.core.blocks.DateBlock(blank=True))]))], blank=True),
        ),
    ]
