# Generated by Django 3.2.12 on 2022-02-11 17:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_alter_portafolioindex_employmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolioindex',
            name='employmentHistory',
            field=wagtail.core.fields.StreamField([('employ', wagtail.core.blocks.StructBlock([('jobTitle', wagtail.core.blocks.CharBlock()), ('employer', wagtail.core.blocks.CharBlock(required=False)), ('city', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('initDate', wagtail.core.blocks.DateBlock(required=False)), ('endDate', wagtail.core.blocks.DateBlock(required=False))]))], blank=True),
        ),
    ]
