# Generated by Django 3.2.12 on 2022-02-11 22:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0008_rename_employmenthistory_portafolioindex_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolioindex',
            name='resume',
        ),
        migrations.AddField(
            model_name='portafolioindex',
            name='certifications',
            field=wagtail.core.fields.StreamField([('certifications', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('institution', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('initDate', wagtail.core.blocks.DateBlock(required=False)), ('endDate', wagtail.core.blocks.DateBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='portafolioindex',
            name='courses',
            field=wagtail.core.fields.StreamField([('courses', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('institution', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('initDate', wagtail.core.blocks.DateBlock(required=False)), ('endDate', wagtail.core.blocks.DateBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='portafolioindex',
            name='employ',
            field=wagtail.core.fields.StreamField([('employ', wagtail.core.blocks.StructBlock([('jobTitle', wagtail.core.blocks.CharBlock()), ('employer', wagtail.core.blocks.CharBlock(required=False)), ('city', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('initDate', wagtail.core.blocks.DateBlock(required=False)), ('endDate', wagtail.core.blocks.DateBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='portafolioindex',
            name='extras',
            field=wagtail.core.fields.StreamField([('extras', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('site', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('initDate', wagtail.core.blocks.DateBlock(required=False)), ('endDate', wagtail.core.blocks.DateBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='portafolioindex',
            name='publications',
            field=wagtail.core.fields.StreamField([('publications', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='portafolioindex',
            name='skills',
            field=wagtail.core.fields.StreamField([('skills', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))]))], blank=True),
        ),
    ]
