# Generated by Django 3.2.12 on 2022-02-15 21:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0009_auto_20220211_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolioindex',
            name='certifications',
            field=wagtail.core.fields.StreamField([('certifications', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('institution', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('initDate', wagtail.core.blocks.DateBlock(required=False)), ('endDate', wagtail.core.blocks.DateBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('rawHTML', wagtail.core.blocks.RawHTMLBlock(required=False))]))], blank=True),
        ),
    ]
