# Generated by Django 3.2.12 on 2022-02-15 23:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0010_alter_portafolioindex_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolioindex',
            name='certifications',
            field=wagtail.core.fields.StreamField([('certifications', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('institution', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('initDate', wagtail.core.blocks.DateBlock(required=False)), ('endDate', wagtail.core.blocks.DateBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('rawHTML', wagtail.core.blocks.RawHTMLBlock(required=False)), ('rawImportScriptCSSAndMeta', wagtail.core.blocks.RawHTMLBlock(help_text='https://www.npmjs.com/package/react-helmet#reference-guide', required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='portafolioindex',
            name='courses',
            field=wagtail.core.fields.StreamField([('courses', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('institution', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('initDate', wagtail.core.blocks.DateBlock(required=False)), ('endDate', wagtail.core.blocks.DateBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('rawHTML', wagtail.core.blocks.RawHTMLBlock(required=False)), ('rawImportScriptCSSAndMeta', wagtail.core.blocks.RawHTMLBlock(help_text='https://www.npmjs.com/package/react-helmet#reference-guide', required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='portafolioindex',
            name='employ',
            field=wagtail.core.fields.StreamField([('employ', wagtail.core.blocks.StructBlock([('jobTitle', wagtail.core.blocks.CharBlock()), ('employer', wagtail.core.blocks.CharBlock(required=False)), ('city', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('initDate', wagtail.core.blocks.DateBlock(required=False)), ('endDate', wagtail.core.blocks.DateBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('rawHTML', wagtail.core.blocks.RawHTMLBlock(required=False)), ('rawImportScriptCSSAndMeta', wagtail.core.blocks.RawHTMLBlock(help_text='https://www.npmjs.com/package/react-helmet#reference-guide', required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='portafolioindex',
            name='extras',
            field=wagtail.core.fields.StreamField([('extras', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('site', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('initDate', wagtail.core.blocks.DateBlock(required=False)), ('endDate', wagtail.core.blocks.DateBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('rawHTML', wagtail.core.blocks.RawHTMLBlock(required=False)), ('rawImportScriptCSSAndMeta', wagtail.core.blocks.RawHTMLBlock(help_text='https://www.npmjs.com/package/react-helmet#reference-guide', required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='portafolioindex',
            name='publications',
            field=wagtail.core.fields.StreamField([('publications', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('rawHTML', wagtail.core.blocks.RawHTMLBlock(required=False)), ('rawImportScriptCSSAndMeta', wagtail.core.blocks.RawHTMLBlock(help_text='https://www.npmjs.com/package/react-helmet#reference-guide', required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='portafolioindex',
            name='skills',
            field=wagtail.core.fields.StreamField([('skills', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('rawHTML', wagtail.core.blocks.RawHTMLBlock(required=False)), ('rawImportScriptCSSAndMeta', wagtail.core.blocks.RawHTMLBlock(help_text='https://www.npmjs.com/package/react-helmet#reference-guide', required=False))]))], blank=True),
        ),
    ]
