# Generated by Django 3.2.12 on 2022-02-16 21:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0011_auto_20220215_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolioindex',
            name='orderData',
            field=wagtail.core.fields.StreamField([('order', wagtail.core.blocks.StructBlock([('block', wagtail.core.blocks.ChoiceBlock(choices=[('tea', 'Tea'), ('coffee', 'Coffee')]))]))], blank=True),
        ),
    ]
