# Generated by Django 3.2.12 on 2022-02-16 21:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0012_portafolioindex_orderdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolioindex',
            name='orderData',
            field=wagtail.core.fields.StreamField([('order', wagtail.core.blocks.StructBlock([('block', wagtail.core.blocks.ChoiceBlock(choices=[('employ', 'Employ'), ('certifications', 'Certifications'), ('courses', 'Courses'), ('extras', 'Extras'), ('skills', 'Skills'), ('publications', 'Publications')]))]))], blank=True),
        ),
    ]
