# Generated by Django 4.0.6 on 2022-07-08 06:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0013_alter_portafolioindex_orderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolioindex',
            name='particle_param',
            field=wagtail.fields.StreamField([('param', wagtail.blocks.RawHTMLBlock(required=False))], blank=True, use_json_field=None),
        ),
    ]
